### ISSUE TITLE
OhMyREPL Won't start on OS X

### ISSUE THREAD

**Issue by joshbode** [KristofferC/OhMyREPL.jl#40]
I'm having trouble with loading OhMyREPL on OS X in Julia 0.5.0.

When I run `using OhMyREPL` at the REPL or in via `.juliarc.jl` file, the whole process hangs, never returning a prompt, needing to be killed with `SIGKILL`.

If I comment out the code to redirect STDERR in OhMyREPL.jl, everything starts fine (but shows the override warnings, of course).

I'm up to date with OhMyREPL and Tokenize packages. I've also tried blowing away both and reinstalling with no success.

**Comment by Ismael-VC** [comment]
:worried: I'm sorry @KristofferC been very busy, but I will check out #38 and try to figure out what is going on, I don't have OSX to test this though, but I haven't checked the travis logs.

**Comment by joshbode** [comment]
no worries - I'll try to do some testing on the `STDERR` redirection code in isolation and see if I can provide more information - what's strange is it _had_ been working, but I'm not sure when it stopped - in any case, I've tried reverting the last few commits without any success.

it might be something else to do with my terminal setup as I've recently adopted tmux, but I don't think that should affect it.

**Comment by joshbode** [comment]
OK - the redirection code works as expected in isolation, e.g.
```julia
function main()
    ORIGINAL_STDERR = STDERR
    err_rd, err_wr = redirect_stderr()
    reader = @async readstring(err_rd)
    warn("Hallo!")
    REDIRECTED_STDERR = STDERR
    err_stream = redirect_stderr(ORIGINAL_STDERR)
    warn("Tschüß!")
end
main()
```
produces only the final warning.

Also, doesn't appear to be related to tmux as the issue persists when I don't use it.

**Comment by KristofferC** [comment]
Hello, I am quite frustrated that a simple thing like temporarily redirecting stderr is causing so much problems. However, I really don't want to spit out 20 warnings everytime julia launches. If you managed to get something to work, do tell.

**Comment by joshbode** [comment]
Huh!

Here it is (for my machine/OS X version/etc) - as soon as the number of bytes written to `stderr` exceeds 512, the process hangs:

```julia
function main()
    ORIGINAL_STDERR = STDERR
    err_rd, err_wr = redirect_stderr()
    reader = @async readstring(err_rd)
    println(STDERR, repeat("X", 2 << 8 + 1))
    REDIRECTED_STDERR = STDERR
    err_stream = redirect_stderr(ORIGINAL_STDERR)
    println(STDERR, "Tschüß!")
end
main()
```

**Comment by KristofferC** [comment]
Can you try again with the newest commit. I believe it should work now. Please reply if it doesn't.

**Comment by joshbode** [comment]
Sorry, I still have the same issue
Still seems to be due to the redirected `STDERR` buffer filling up, at least for my install.
Could be an issue with Julia itself?

**Comment by KristofferC** [comment]
The build bots on Windows started working so I thought it would be fixed here too. I'm not sure where the problem is. For now, all I can say is that you can either remove the redirection (will give you annoying messages on starting julia) or if you don't care about the new error messages you can just delete the whole chunk of code where it is included. :(

**Comment by joshbode** [comment]
Thanks for that - I'll raise an issue with Julia about the redirect issue and I'll get back to you if I find a workaround :)

**Comment by KristofferC** [comment]
Can you please try https://github.com/KristofferC/OhMyREPL.jl/pull/52 and see if that helps.

**Comment by joshbode** [comment]
It does! Thank you for that!
Closing :)
